# Generated by Django 4.0 on 2021-12-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('did', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'studentdetails',
                'verbose_name_plural': 'studentdetails',
            },
        ),
    ]
